site_name: {{ cookiecutter.project_name }} (Project name)

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - index.md
  - tutorials.md
  - how-to-guides.md
  - reference.md
  - explanation.md
